### PR TITLE
Add `all_true` and `any_true`

### PR DESCRIPTION
**Pull request by penzn**
Add `all_true` and `any_true` for integer intputs up to 32-bit lanes.

### CODE REVIEW

**Comment by arunetm** [comment]
Is there broader hardware support for the > 128-bit versions of these ops?

**Comment by penzn** [comment]
Yeah, there are "packed equal" operations longer than 128 bits.

**Comment by Yaffle** [comment]
Should it work only for mask vectors?

**Comment by ppenzin** [comment]
Sorry was between two accounts, didn't see the question. It should work without masking, though it is easy to implement that via masking as well.

**Pull request merged**
